# 5-drum mapping for ENST and MDB, from ADTOF
ENST_MAPPING = {
    "bd": 0,

    "sd": 1,
    "sd-": 1,
    "sweep": 1,
    "rs": 1,
    "sticks": 1,
    "cs": 1,

    "mt": 2,
    "mtr": 2,
    "lmt": 2,
    "lt": 2,
    "ltr": 2,
    "lft": 2,

    "chh": 3,
    "ohh": 3,

    "cr": 4,
    "spl": 4,
    "ch": 4,
    "rc": 4,
    "c": 4,
    "cb": 4,
}

MDB_MAPPING = {
    "KD": 0, #'kick drum'

    "SD": 1, #'snare drum',
    "SDB": 1, #'snare drum: brush',
    "SDD": 1, #'snare drum: drag',
    "SDF": 1, #'snare drum: flam',
    "SDG": 1, #'snare drum: ghost note',
    "SDNS": 1, #'snare drum: no snare',
    "SST": 1, #'side stick',

    "HIT": 2, #'high tom',
    "MHT": 2, #'high-mid tom',
    "HFT": 2, #'high floor tom',
    "LFT": 2, #'low floor tom',

    "CHH": 3, #'hi-hat: closed',
    "OHH": 3, #'hi-hat: open',
    "PHH": 3, #'hi-hat: pedal',
    "TMB": 3, #'tambourine',

    "RDC": 4, #'ride cymbal',
    "RDB": 4, #'ride cymbal: bell',
    "CRC": 4, #'crash cymbal',
    "CHC": 4, #'china cymbal',
    "SPC": 4, #'splash cymbal',
}

# 5-drum mapping for Roland MIDI, from "https://arxiv.org/pdf/1905.06118" (and from "https://github.com/khiner/DrumClassification/blob/main/create_label_mapping.py" and "https://soundprogramming.net/file-formats/general-midi-drum-note-numbers/")
ROLAND_MIDI_MAPPING = {
    35: 0, #'Acoustic Bass Drum',
    36: 0, #'Bass Drum',

    37: 1, #'Side Stick',
    38: 1, #'Acoustic Snare',
    39: 1, #'Hand Clap',
    40: 1, #'Electric Snare',

    41: 2, #'Low Floor Tom',
    43: 2, #'High Floor Tom',
    45: 2, #'Low Tom',
    47: 2, #'Low-Mid Tom',
    48: 2, #'Hi-Mid Tom',
    50: 2, #'High Tom',
    58: 2, #'High Floor Tom (Rim)', -Manually retrieved from Roland TD-11

    22: 3, #'Hi-Hat Open (Edge)',   -Manually retrieved from Roland TD-11
    26: 3, #'Hi-Hat Closed (Edge)', -Manually retrieved from Roland TD-11
    42: 3, #'Closed Hi-Hat',
    44: 3, #'Pedal Hi-Hat',
    46: 3, #'Open Hi-Hat',
    54: 3, #'Tambourine',

    49: 4, #'Crash Cymbal 1',
    51: 4, #'Ride Cymbal 1',
    52: 4, #'Chinese Cymbal',
    53: 4, #'Ride Bell',
    55: 4, #'Splash Cymbal',
    56: 4, #'Cowbell',
    57: 4, #'Crash Cymbal 2',
    59: 4, #'Ride Cymbal 2',

    27: None, #'High Q (GM2)',
    28: None, #'Slap (GM2)',
    29: None, #'Scratch Push (GM2)',
    30: None, #'Scratch Pull (GM2)',
    31: None, #'Sticks (GM2)',
    32: None, #'Square Click (GM2)',
    33: None, #'Metronome Click (GM2)',
    34: None, #'Metronome Bell (GM2)',
    60: None, #'Hi Bongo',
    61: None, #'Low Bongo',
    62: None, #'Mute Hi Conga',
    63: None, #'Open Hi Conga',
    64: None, #'Low Conga',
    65: None, #'High Timbale',
    66: None, #'Low Timbale',
    67: None, #'High Agogo',
    68: None, #'Low Agogo',
    69: None, #'Cabasa',
    70: None, #'Maracas',
    71: None, #'Short Whistle',
    72: None, #'Long Whistle',
    73: None, #'Short Guiro',
    74: None, #'Long Guiro',
    75: None, #'Claves',
    76: None, #'Hi Wood Block',
    77: None, #'Low Wood Block',
    78: None, #'Mute Cuica',
    79: None, #'Open Cuica',
    80: None, #'Mute Triangle',
    81: None, #'Open Triangle',
    82: None, #'Shaker (GM2)',
    83: None, #'Jingle Bell (GM2)',
    84: None, #'Belltree (GM2)',
    85: None, #'Castanets (GM2)',
    86: None, #'Mute Surdo (GM2)',
    87: None, #'Open Surdo (GM2)',
}

# 5-drum mapping for MIDI, from "https://github.com/khiner/DrumClassification/blob/main/create_label_mapping.py" and "https://soundprogramming.net/file-formats/general-midi-drum-note-numbers/"
MIDI_MAPPING = {
    35: 0, #'Acoustic Bass Drum',
    36: 0, #'Bass Drum',

    37: 1, #'Side Stick',
    38: 1, #'Acoustic Snare',
    39: 1, #'Hand Clap',
    40: 1, #'Electric Snare',

    41: 2, #'Low Floor Tom',
    43: 2, #'High Floor Tom',
    45: 2, #'Low Tom',
    47: 2, #'Low-Mid Tom',
    48: 2, #'Hi-Mid Tom',
    50: 2, #'High Tom',

    42: 3, #'Closed Hi-Hat',
    44: 3, #'Pedal Hi-Hat',
    46: 3, #'Open Hi-Hat',
    54: 3, #'Tambourine',

    49: 4, #'Crash Cymbal 1',
    51: 4, #'Ride Cymbal 1',
    52: 4, #'Chinese Cymbal',
    53: 4, #'Ride Bell',
    55: 4, #'Splash Cymbal',
    56: 4, #'Cowbell',
    57: 4, #'Crash Cymbal 2',
    59: 4, #'Ride Cymbal 2',

    27: None, #'High Q (GM2)',
    28: None, #'Slap (GM2)',
    29: None, #'Scratch Push (GM2)',
    30: None, #'Scratch Pull (GM2)',
    31: None, #'Sticks (GM2)',
    32: None, #'Square Click (GM2)',
    33: None, #'Metronome Click (GM2)',
    34: None, #'Metronome Bell (GM2)',
    58: None, #'Vibraslap'
    60: None, #'Hi Bongo',
    61: None, #'Low Bongo',
    62: None, #'Mute Hi Conga',
    63: None, #'Open Hi Conga',
    64: None, #'Low Conga',
    65: None, #'High Timbale',
    66: None, #'Low Timbale',
    67: None, #'High Agogo',
    68: None, #'Low Agogo',
    69: None, #'Cabasa',
    70: None, #'Maracas',
    71: None, #'Short Whistle',
    72: None, #'Long Whistle',
    73: None, #'Short Guiro',
    74: None, #'Long Guiro',
    75: None, #'Claves',
    76: None, #'Hi Wood Block',
    77: None, #'Low Wood Block',
    78: None, #'Mute Cuica',
    79: None, #'Open Cuica',
    80: None, #'Mute Triangle',
    81: None, #'Open Triangle',
    82: None, #'Shaker (GM2)',
    83: None, #'Jingle Bell (GM2)',
    84: None, #'Belltree (GM2)',
    85: None, #'Castanets (GM2)',
    86: None, #'Mute Surdo (GM2)',
    87: None, #'Open Surdo (GM2)',
}
